"""empty message

Revision ID: e0e89182d57f
Revises: 1579e65bb856
Create Date: 2022-07-17 15:21:31.568640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1579e65bb856"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("contents", sa.String(length=10000), nullable=False),
        sa.Column("writer", sa.String(length=30), nullable=False),
        sa.Column("password", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.String(length=30), nullable=False),
        sa.Column("updated_at", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boards_title"), "boards", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_boards_title"), table_name="boards")
    op.drop_table("boards")
    # ### end Alembic commands ###
