"""create comments table

Revision ID: 9a1ab00ea112
Revises: 1579e65bb856
Create Date: 2022-07-17 15:32:04.234525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a1ab00ea112"
down_revision = "1579e65bb856"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contents", sa.String(length=1000), nullable=False),
        sa.Column("writer", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.String(length=30), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["boards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
