"""create keywords table

Revision ID: a1dadc0b48ee
Revises: 9a1ab00ea112
Create Date: 2022-07-17 21:51:22.709950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1dadc0b48ee"
down_revision = "9a1ab00ea112"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=50), nullable=False),
        sa.Column("writer", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("comments_ibfk_1", "comments", type_="foreignkey")
    op.create_foreign_key(None, "comments", "boards", ["board_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_ibfk_1",
        "comments",
        "boards",
        ["board_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_table("keywords")
    # ### end Alembic commands ###
